name: GiftCardSite GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Navigate to repository and execute build
        run: |
          cd ${{ github.workspace }}
          cd GiftcardSite
          export SECRET_KEY='kmgysa#fz+9(z1*=c0ydrjizk*7sthm2ga1z4=^61$cxcq8b$l'
          sudo pip3 install django
          sudo pip3 install django-cryptography
          python manage.py makemigrations LegacySite
          python manage.py makemigrations
          python manage.py migrate
          python3 manage.py test LegacySite
      - run: echo "🍏 This job's status is ${{ job.status }}."